name: CRIS
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - scipy
  - wandb
  - psutil
  - pyyaml
  - pip
  - pip:
    - yfinance
    - antropy
    - pydantic>=2.0
