"""
CRIS Macro Environmental Intelligence Configuration (Refactored)
"""

from pathlib import Path

# Paths
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data" / "macro"
OUTPUT_DIR = BASE_DIR / "outputs" / "macro"

# Ensure output dir exists
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Regime Detection Thresholds
STRESS_THRESHOLD = 0.45
CAUTION_THRESHOLD = 0.20
CONFIDENCE_WINDOW = 24 # Months

# Rolling Windows
ROLLING_WINDOW_SMALL = 21
ROLLING_WINDOW_MEDIUM = 63
ROLLING_WINDOW_LARGE = 252
DEFAULT_LOOKBACK_WINDOW = 252
DEFAULT_LAG = 1

# Alarm Thresholds
PERM_ALARM_DROP_THRESHOLD = 0.15
SHOCK_INTENSITY_THRESHOLD = 0.65
EROSION_STRENGTH_THRESHOLD = 0.50
FAST_VOL_SPIKE_THRESHOLD = 2.0
FAST_VOL_EXTREME_THRESHOLD = 5.0
CONFIDENCE_FLOOR = 0.10
VOL_STRESS_MULTIPLIER = 1.5
VOL_CRITICAL_MULTIPLIER = 3.0
STRESS_PERSISTENCE_DAYS = 21
CRITICAL_PERSISTENCE_DAYS = 5
ENTROPY_STRESS_THRESHOLD = 0.80
ENTROPY_CRITICAL_THRESHOLD = 1.50
# Transition & Evolution
FIELD_EVOLUTION_WINDOW = 10
TRANSITION_VELOCITY_THRESHOLD = 0.05
MAX_LOGIT_SHIFT = 2.0
BETA_STRESS = 1.2
STRESS_ANCHOR = 0.25

# Decay & Smoothing
DECAY_RATE_FAST = 0.95
DECAY_RATE_SLOW = 0.99
SMOOTHING_WINDOW = 5

# Uncertainty & Stability
UNCERTAINTY_THRESHOLD = 0.35
UNCERTAINTY_DISAGREEMENT_THRESHOLD = 0.30
UNCERTAINTY_LOW_CONFIDENCE_THRESHOLD = 0.40
STABILITY_THRESHOLD = 0.80

# LSTM Architecture
LSTM_HIDDEN_DIM = 32
LSTM_NUM_LAYERS = 2
LSTM_SEQUENCE_LENGTH = 21
LSTM_FEATURE_DIM = 6
LSTM_INFLUENCE_CAP = 0.30

# Convergence Weighting
WEIGHT_PRIOR_FAST = 0.35
WEIGHT_PRIOR_SLOW = 0.40
WEIGHT_PRIOR_DECAY = 0.25
PERSISTENCE_SLOW_BOOST_RATE = 0.005
PERSISTENCE_DECAY_BOOST_RATE = 0.003
WEIGHT_SMOOTHING_ALPHA = 0.15
RECOVERY_VELOCITY_THRESHOLD = 0.05
PARTNER_INFLUENCE_CAP = 0.10

# Calibration Baselines
SPY_BASELINE_VOL = 0.012
SPY_BASELINE_PERM_ENTROPY = 0.92
ENTROPY_SAMPLE_BASELINE = 1.4
